# Change baseurl before deploy
baseurl = "https://www.mondefetch.com"
languageCode = "en-us"
title = "mondeFetch"

# --- DÜZELTME BURADA ---
# Analytics kodunu buraya, en tepeye 'googleAnalytics' olarak ekliyoruz.
googleAnalytics = "G-FP1LR9Q27W" 

# [params.analytics] <- BU BÖLÜMÜ SİLİN, ARTIK GEREKSİZ.
# google = "G-FP1LR9Q27W" <- BU SATIRI DA SİLİN.

# Theme i18n support
defaultContentLanguage = "en"
hasCJKLanguage = false
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5